### ISSUE TITLE
[Sidebar] Trie par medium

### ISSUE THREAD

**Issue by BenjmnG** [tchak/klown-website#11]
Dans la SideBar, il est possible de trier les items par medium.

Ce trie est censé être opéré par des `input type=radio` name="sort-by-medium" id="medium-3"  et des règles CSS permettant de d'obfusquer les items non-désirés.

Cela implique, 
- à la génération de la page, de lister l'ensemble des médiums présent dans la liste
- de convertir les dénominations en un numéro de série (1, 2, 3,...) afin de coller avec les règles CSS génériques
- d'introduire en amont de la SideBar un nombre d'`input` correspondant au nombre de Medium
- de générer une liste des Mediums dans l'élément `sort-options`

**Comment by tchak** [comment]
done
