### ISSUE TITLE
[Pages] Les carrousel peuvent contenir des images aux hauteurs divergentes. Le carrousel devrait prendre la hauteur de la première image

### ISSUE THREAD

**Issue by BenjmnG** [tchak/klown-website#27]
Sur le crrousel, une fonction autoHeight() s’exécute à chaque changement de slide..
Malheureusement, cette fonction ne s’exécute pas encore `onLoad` (voir Transformation/dispositif-lumineux-morphique)
Nous devrions trouver un moyen de brider la hauteur du carrousel une fois la première slide chargée.

Proposition de code : 

```
      if(img.complete) {
        autoHeight(0)
      } else {
        img.addEventListener('load', autoHeight(0))
      }
```

**Comment by BenjmnG** [comment]
En conséquence, l'élément Carrousel acquiert un attribut `max-height` 
Si nous changeons de page ( ex de https://klown.netlify.app/piece/dispositif-lumineux-morphique à une autre œuvre) cet attribut spécifique persiste sur la nouvelle page et cause des bugs d'affichage.

![image](https://user-images.githubusercontent.com/10298798/148579009-fa980ac5-e0d0-4b65-8aa7-417e13e11816.png)

**Comment by tchak** [comment]
done
