### ISSUE TITLE
[Page Pièce] La page active la fonction autoHeight on Resize

### ISSUE THREAD

**Issue by BenjmnG** [tchak/klown-website#28]
Je pense que ma fonction est inopérante. Sans doute car mal appelée.

https://github.com/tchak/klown-website/blob/6d42cb21d14201933dcd4efbc67e6eefd2e6f7d9/app/routes/piece.%24slug.tsx#L188

**Comment by BenjmnG** [comment]
Linked to #27

**Comment by tchak** [comment]
done
